src/test/01-manipulating-fabrics.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* C8 Version:

list user fabrics

---

package-lock.json
package.json
src/collection.ts
src/stream.ts
src/util/helper.ts
src/util/webSocket.ts
src/util/webSocket.web.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* C8 Version:

 support for websocket for node and browser

---

docs/Reference/Cursor.md
docs/Reference/Database/FabricManipulation.md
docs/Reference/Database/Queries.md
docs/Reference/Graph/Vertices.md
src/c8ql-query.ts
src/cursor.ts
src/fabric.ts
src/graph.ts
src/stream.ts
src/test/01-manipulating-fabrics.ts
src/test/08-cursors.ts
src/test/22-util-helper.ts
src/util/helper.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* C8 Version:

api modifications

---

.gitignore
docs/Reference/README.md
docs/Reference/UserOperations.md
src/fabric.ts
src/test/30-user-management.ts
src/user.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* C8 Version:

Jsc8 user management

---

examples/01-geo-distributed-apps.js
examples/02-CDN.js
examples/03-streams.js
examples/04-geo-distributed-collections.js
examples/restql.js

Added js examples for repl it

---

examples/05-geo-distributed-databases.js

Added geo distributed database (callback) example

Added geo distributed database (callback) example

---

examples/03-streams.js

Fixed the streams example

---

docs/Reference/Stream.md
src/stream.ts
src/test/28-manipulating-streams.ts

Removed the unused API calls and the corresponding test cases and references in the docs.
https://github.com/Macrometacorp/C8Platform/issues/632
Ran the existing test script present in package.json with the appropriate file name.
* C8 Version:
@lohaniabhishek

Removing unused APIs

---

src/test/01-manipulating-fabrics.ts
src/test/02-accessing-collections.ts
src/test/03-accessing-graphs.ts
src/test/04-transactions.ts
src/test/05-c8ql-queries.ts
src/test/07-routes.ts
src/test/08-cursors.ts
src/test/09-collection-metadata.ts
src/test/10-manipulating-collections.ts
src/test/11-managing-indexes.ts
src/test/14-document-collections.ts
src/test/15-edge-collections.ts
src/test/16-graphs.ts
src/test/17-graph-vertices.ts
src/test/18-graph-edges.ts
src/test/19-graph-vertex-collections.ts
src/test/23-c8ql-queries-stream.ts
src/test/27-manipulating-tenants.ts
src/test/29-manipulating-spot.ts
src/test/30-user-management.ts

Fixed the failing test cases.
https://github.com/Macrometacorp/C8Platform/issues/596
Ran the npm devTest script.
* C8 Version:
@lohaniabhishek

Fixing test cases - auth

---

docs/Reference/Stream.md
src/stream.ts
src/test/28-manipulating-streams.ts

Added test cases to streams.
https://github.com/Macrometacorp/C8Platform/issues/596
Using npm script.
* C8 Version:
@lohaniabhishek

Adding test cases for streams

---

docs/Reference/Pipeline.md
src/fabric.ts
src/pipeline.ts
src/test/32-pipelines.ts

Listed all APIs and the test cases. in the driver
https://github.com/Macrometacorp/C8Platform/issues/618

Pipeline API changes

---

docs/GettingStarted/README.md
package-lock.json
package.json
src/test/10-manipulating-collections.ts

Added test cases to check the creation of local collections.
* C8 Version:

Local collections

---

docs/Reference/Event.md
src/event.ts
src/fabric.ts
src/test/33-events.ts

Driver changes for the event service APIs and documentation for the same.
https://github.com/Macrometacorp/C8Platform/issues/718
* C8 Version:

Event service APIs and markdown

---

README.md
docs/GettingStarted/README.md
docs/RESTQL.md
docs/Reference/Collection/CollectionManipulation.md
docs/Reference/Collection/DocumentCollection.md
docs/Reference/Collection/DocumentManipulation.md
docs/Reference/Collection/EdgeCollection.md
docs/Reference/Collection/Indexes.md
docs/Reference/Collection/README.md
docs/Reference/Cursor.md
docs/Reference/Database/C8qlUserFunctions.md
docs/Reference/Database/CollectionAccess.md
docs/Reference/Database/FabricManipulation.md
docs/Reference/Database/GraphAccess.md
docs/Reference/Database/HttpRoutes.md
docs/Reference/Database/Queries.md
docs/Reference/Database/README.md
docs/Reference/Database/Transactions.md
docs/Reference/Database/ViewAccess.md
docs/Reference/Event.md
docs/Reference/Graph/EdgeCollection.md
docs/Reference/Graph/Edges.md
docs/Reference/Graph/README.md
docs/Reference/Graph/VertexCollection.md
docs/Reference/Graph/Vertices.md
docs/Reference/Pipeline.md
docs/Reference/Route.md
docs/Reference/Stream.md
docs/Reference/Tenant.md
docs/Reference/UserOperations.md

Doc update

---

docs/GettingStarted/README.md
docs/Reference/Tenant.md
src/tenant.ts

Createtenant dclist

---

src/stream.ts

removed logs

---

src/stream.ts

removed noop producer for consumers
* C8 Version:

removed noop producer for consumer

---

src/client.ts

- added localDC call instead getDcList

Region issue in streams

---

.prettierignore
.prettierrc.json
.vscode/settings.json
docs/Reference/ViewManipulation.md
src/client.ts
src/search.ts
src/test/36-search.ts

- Added view documentation and done minor changes

View Documentation

---

README.md

Corrected code in readme

---

docs/Reference/ViewManipulation.md
src/client.ts
src/search.ts

In this pr I have added properties field and primary sort to be included in createView of search
Fixes # (issue)https://macrometa.atlassian.net/browse/CLI-27

Added missing properties field and primary sort in search

---

src/graph.ts

This pr adds missing graph functions and this is related to these tickets
https://macrometa.atlassian.net/browse/CLI-45
https://macrometa.atlassian.net/browse/CLI-53
https://macrometa.atlassian.net/browse/CLI-55
https://macrometa.atlassian.net/browse/CLI-56

Add graph missing parameters

---

src/graph.ts

In this pr i have added optns to the document method of edge as well. 
This is related to this ticket
https://macrometa.atlassian.net/browse/CLI-63

 Add optns to graph edge

---

docs/Reference/ApiKeys.md
docs/Reference/UserOperations.md
src/apiKeys.ts
src/client.ts
src/test/30-user-management.ts
src/user.ts

This pr add user attributes' api to jsc8 . 
It is related to the below ticket
https://macrometa.atlassian.net/browse/CLI-60

Cli 60 attributes in user api

---

src/graph.ts

This pr return the whole objret of graph result
https://macrometa.atlassian.net/browse/CLI-53

Returning whole objects for graph

---

docs/RESTQL.md
src/client.ts
src/fabric.ts

This pr is related to this issue 
https://macrometa.atlassian.net/browse/CLI-64

Add restql cursor command

---

docs/Reference/Collection/CollectionManipulation.md
package-lock.json
package.json
src/collection.ts

In this ticket we have update the collectionupdateproperties optional

Added optional to has stream method

---

docs/Reference/Collection/KeyValueCollectionManipulation.md

Updated readme descriptions to be correct.  DOC-136

Fixed descriptions

---

docs/Reference/Tenant.md

Moved client.listTenants to the Admin Only section.  DOC-97

Moved client.listTenants to Admin Only

---

src/fabric.ts
src/test/40-sql-queries.ts

Added support for sql queries.

Added support for sql queries

---

src/fabric.ts
src/streamapps.ts

createStreamApp and updateApplication do not seem to work because the body is getting stringified and then another string conversion takes place here https://github.com/Macrometacorp/jsC8/blob/master/src/connection.ts#L365 .. which leads to additional "/" coming in definition field of the body leading to failure of these functions. We can instead rely on the stringify function already present here and simply remove the stringify inside the functions: https://github.com/Macrometacorp/jsC8/blob/master/src/connection.ts#L362
Use the scripts mentioned here in Javascript tab to test:
https://macrometa.com/docs/cep/stream-workers-example
* C8 Version:

Fixing createStreamApp and updateApplication functions

---

package-lock.json
package.json

We have just changed version number  0.17.11 and published it to npm.
We have run unit tests in the project.

New version update 0.17.11

---

docs/RESTQL.md
src/client.ts
src/fabric.ts

Adding batchSize option to the RestQL
- [+] Bug fix (non-breaking change which fixes an issue)
- [-] New feature (non-breaking change which adds functionality)
- [-] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [+] This change requires a documentation update
Manually test with batchSize and bindVars 
@dlozina

RESTQL fix for batchSize
